apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-m4ya
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-m4ya
    app.kubernetes.io/part-of: cin4s-839-0079-app
  name: devfile-sample-m4ya
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-m4ya
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-m4ya
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0079-tenant/cin4s-839-0079-app/devfile-sample-m4ya@sha256:88d3837efa1dfaa0d8b497508ec52a8c1e86b83086ae9a15bb5441370ffb7333
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
