apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-m4ya
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-m4ya
    app.kubernetes.io/part-of: cin4s-839-0079-app
  name: devfile-sample-m4ya5u2r
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-m4ya
    weight: null
status: {}
